### PR TITLE
Prep 0.30.2 release.

### LINKED ISSUE #38: Update pypi release for `pip install google-cloud-happybase`
The release present in pypi (https://pypi.org/project/google-cloud-happybase/) is severely outdated. Please make a release reflecting the changes in the bigtable api.

### PR DESCRIPTION
**Pull request by tseaver**
Closes #38.

### CODE REVIEW

**Comment by sduskis** [comment]
@tseaver, I think we ought to hold off upgrading until we fix https://github.com/GoogleCloudPlatform/google-cloud-python/issues/5876

**Comment by tseaver** [comment]
@sduskis OK.

**Comment by tseaver** [comment]
@sduskis PTAL:  I've updated to require `google-cloud-bigtable>=0.30.2,<0.31dev`, and bumped the version here to match.

**Comment by tseaver** [comment]
@sduskis I added a changelog entry for PR #42, which I just merged. PTAL.

**Comment by Froskekongen** [comment]
@tseaver: Is the requirement of `<0.31dev` in `setup.py` strictly necessary?
@sduskis: Can you approve this PR, so that a new release on pypi becomes available?

**Comment by Froskekongen** [comment]
In `connection.py` it seems that `instance.copy()` is still being used. Isn't this deprecated behaviour?

**Comment by tseaver** [comment]
@Froskekongen 

>  Is the requirement of <0.31dev in setup.py strictly necessary?

Until `google-cloud-bigtable` has a release at GA status, breaking changes are possible (even likely).  We therefore need to make a new release of `google-cloud-happybase` for pretty much any non-patch release of `google-cloud-bigtable`.

**Comment by tseaver** [comment]
@Froskekongen 

> In `connection.py` it seems that `instance.copy()` is still being used. Isn't this deprecated behaviour?

Thanks for the catch!  Tracked in #46.

**Comment by sduskis** [comment]
@tseaver, I updated the changelog to include issue #44, and update the PR references to include URLs as per the newer versions of releasetool.

**Pull request merged**
