### PR TITLE
Release google-cloud-python-happybase 0.32.0

### PR DESCRIPTION
**Pull request by crwilcox**
This pull request was generated using releasetool.

### CODE REVIEW

**Comment by sduskis** [comment]
@crwilcox, it looks like there's a failing unit test.  I'm going to try to rerun, 

For posterity, here's the failure from TestBatch.test_send:

>        self.assertEqual(table._low_level_table.rows_mutate,
>                        [row1, row2])

This needs to be a comparison of sets rather than lists.

**Comment by tseaver** [comment]
@crwilcox I rebased the branch to pick up the unit test fix from #53.

**Comment by tseaver** [comment]
@crwilcox The lint failure is real:  `google.cloud.happybase.pool.Pool.__init__` actually *does* make an invalid call to `google.cloud.happybase.connection._get_instance`:  its unit tests mock that away.

**Comment by crwilcox** [comment]
Release is at https://github.com/googleapis/google-cloud-python-happybase/releases/tag/google-cloud-python-happybase-2018.12.17

**Pull request merged**
